language: node_js

node_js:
  - "8"

install:
  - npm install
  - npm run build
  - cd theme/doc
  - npm install

deploy:
  local_dir: ./public
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master