language: node_js

node_js:
  - "8"

install:
  - npm install
  - cd themes/doc
  - npm install --prod
  - cd ../../
  - npm run build

deploy:
  target_branch: master
  local_dir: ./public
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: source